import { Graph, Node, LinkData, FloatingLinkData, MoveAreaLogic, LinkLogic, NodeLogic } from "@ui/node_view.slint";
import { Palette, PaletteSearch } from "@ui/command_palette.slint";
import { Timeline } from "@ui/timeline.slint";

export {
    NodeLogic,
    MoveAreaLogic,
    LinkLogic,
    PaletteSearch
}

export component View inherits Window {
    in property <[Node]> nodes;
    in property <[LinkData]> links;
    in property <FloatingLinkData> floating;

    preferred-height: 10cm;
    preferred-width: 20cm;

    title: "Kira Studio";

    init() => {
        focus.focus();
    }

    focus := FocusScope {

        VerticalLayout {
            Graph {
                nodes: nodes;
                links: links;
                floating: floating;
            }


            timeline := Timeline {
                width: 100%;
                height: 1cm;
            }
        }

        palette := Palette {
            visible: false;

            closed() => {
                focus.focus();
            }
        }

        // TODO: Hide palette when esc is pressed.
        key-pressed(event) => {
            if (event.text == Key.Escape) {
                palette.hide();
                return EventResult.accept;
            }

            if (event.modifiers.control && event.text == "k") {
                palette.toggle();
                return EventResult.accept;
            }

            return EventResult.reject;
        }
    }
}
