import { Graph, NodeData, LinkData, FloatingLinkData, MoveAreaLogic, LinkLogic, NodeLogic } from "node_view.slint";
import { SearchItem, Palette, PaletteSearch } from "command_palette.slint";
import { Timeline } from "timeline.slint";
import { Tabs, TabLogic } from "tabs.slint";
import { Menu } from "menu.slint";

export {
    PointerEventKind,
    NodeLogic,
    MoveAreaLogic,
    LinkLogic,
    PaletteSearch,
    TabLogic
}

export component View inherits Window {
    in property <[NodeData]> nodes;
    in property <[LinkData]> links;
    in property <FloatingLinkData> floating;
    in property <int> selected_tab;
    in property <[string]> tab_names;
    in property <[SearchItem]> command_palette_results;

    preferred-height: 20cm;
    preferred-width: 30cm;

    title: "Kira Studio";
    background: #0F0F0F;

    init() => {
        focus.focus();
    }

    function any_tab_selected() -> bool {
        return selected_tab >= 0;
    }

    focus := FocusScope {

        VerticalLayout {
            Menu { }
            Tabs {
                selected_tab: selected_tab;
                tab_names: tab_names;
            }
            Graph {
                visible: any_tab_selected();
                nodes: nodes;
                links: links;
                floating: floating;
            }
            timeline := Timeline {
                visible: any_tab_selected();
                width: 100%;
                height: 1cm;
            }
        }
        palette := Palette {
            visible: false;
            results: command_palette_results;

            closed() => {
                focus.focus();
            }
        }
        key-pressed(event) => {
            if (event.text == Key.Escape) {
                palette.hide();
                return EventResult.accept;
            }

            if (event.modifiers.control && event.text == "k") {
                palette.toggle();
                return EventResult.accept;
            }

            return EventResult.reject;
        }
    }
}
