import { CheckBox } from "std-widgets.slint";

component MenuPopupItem inherits Rectangle {
    in property <string> name;
    callback clicked();

    background: ta.has-hover ? #3f3f3f : #2f2f2f;
    preferred-width: txt.preferred-width + 20px;
    preferred-height: txt.preferred-height + 5px ;

    HorizontalLayout {
        alignment: LayoutAlignment.start;
        padding-left: 10px;
        padding-top: 2.5px;
        txt := Text {
            horizontal-alignment: TextHorizontalAlignment.left;
            font-size: 8pt;
            color: white;
            text: name;
        }
    }
    ta := TouchArea {
        clicked => { root.clicked(); }
    }
}

component TopLevelMenu inherits Rectangle {
    in property <string> name;

    preferred-width: txt.preferred-width + 20px;
    preferred-height: txt.preferred-height + 5px;
    padding-left: 1px;

    background: ta.has-hover ? #2f2f2f: #010101;
    txt := Text {
        horizontal-alignment: TextHorizontalAlignment.left;
        font-size: 8pt;
        color: white;
        text: name;
    }
    ta := TouchArea {
        clicked => {
            popup.show();
        }
    }
    popup := PopupWindow {
        x: 0px;
        y: parent.height;
        VerticalLayout { 
            @children
        }
    }
}

export global MenuLogic { 
    callback open_file();
    callback save();
    callback save_as();
}

export component Menu inherits Rectangle {
    preferred-width: 100%;
    background: #010101;
    HorizontalLayout {
        alignment: LayoutAlignment.start;
        TopLevelMenu {
            name: "File";
            MenuPopupItem  {
                name: "Open File...";
                clicked => { MenuLogic.open_file(); }
            }
            MenuPopupItem  {
                name: "Save";
                clicked => { MenuLogic.save(); }
            }
            MenuPopupItem  {
                name: "Save as...";
                clicked => { MenuLogic.save_as(); }
            }
            // MenuPopupItem  { name: "Exit"; }
        }
        // TopLevelMenu {
        //     name: "Edit";
        //     MenuPopupItem  { name: "Lorem"; }
        //     MenuPopupItem  { name: "Ipsum"; }
        // }
    }
}
