export global FieldType {
    in-out property<string> select : "Kira__Reserved_Select";
    in-out property<string> string-input : "Kira__Reserved_String";
    in-out property<string> int-input : "Kira__Reserved_Int";
    in-out property<string> float-input : "Kira__Reserved_Float";
    in-out property<string> image-output: "Kira__Reserved_Image";
}

export struct Slot {
    name: string,
    ty: string,
}

export struct Field {
    name: string,
    ty: string,
    options: [StandardListViewItem],
    default_text: string,
    default_value: float,
    default_option: int,
    min: float,
    max: float,
    step: float,
    image: image,
}

export struct NodeData { 
    x: length,
    y: length,
    width: length,
    text: string,
    inputs: [Slot],
    outputs: [Slot],
    input_fields: [Field],
}

export struct LinkData {
    src: int,
    src_slot: int,
    dst: int,
    dst_slot: int,
    ty: string,
}

export enum FloatingState {
    src_attached,
    dst_attached,
    none,
}

export struct FloatingLinkData {
    floating_state: FloatingState,
    node: int,
    node_slot: int,
    ty: string,
    x: length,
    y: length,
}
